jQuery = $

$ ->
  departements = 
    [
      {id:"01","dp":"Ain"},
      {id:"02","dp":"Aisne"},
      {id:"03","dp":"Allier"},
      {id:"04","dp":"Alpes-de-Haute-Provence"},
      {id:"05","dp":"Hautes-Alpes"},
      {id:"06","dp":"Alpes-Maritimes"},
      {id:"07","dp":"Ardèche"},
      {id:"08","dp":"Ardennes"},
      {id:"09","dp":"Ariège"},
      {id:"10","dp":"Aube"},
      {id:"11","dp":"Aude"},
      {id:"12","dp":"Aveyron"},
      {id:"13","dp":"Bouches-du-Rhône"},
      {id:"14","dp":"Calvados"},
      {id:"15","dp":"Cantal"},
      {id:"16","dp":"Charente"},
      {id:"17","dp":"Charente-Maritime"},
      {id:"18","dp":"Cher"},
      {id:"19","dp":"Corrèze"},
      {id:"20","dp":"Corse"},
      {id:"21","dp":"Côte-d'Or"},
      {id:"22","dp":"Côtes d'Armor"},
      {id:"23","dp":"Creuse"},
      {id:"24","dp":"Dordogne"},
      {id:"25","dp":"Doubs"},
      {id:"26","dp":"Drôme"},
      {id:"27","dp":"Eure"},
      {id:"28","dp":"Eure-et-Loir"},
      {id:"29","dp":"Finistère"},
      {id:"30","dp":"Gard"},
      {id:"31","dp":"Haute-Garonne"},
      {id:"32","dp":"Gers"},
      {id:"33","dp":"Gironde"},
      {id:"34","dp":"Hérault"},
      {id:"35","dp":"Ille-et-Vilaine"},
      {id:"36","dp":"Indre"},
      {id:"37","dp":"Indre-et-Loire"},
      {id:"38","dp":"Isère"},
      {id:"39","dp":"Jura"},
      {id:"40","dp":"Landes"},
      {id:"41","dp":"Loir-et-Cher"},
      {id:"42","dp":"Loire"},
      {id:"43","dp":"Haute-Loire"},
      {id:"44","dp":"Loire-Atlantique"},
      {id:"45","dp":"Loiret"},
      {id:"46","dp":"Lot"},
      {id:"47","dp":"Lot-et-Garonne"},
      {id:"48","dp":"Lozère"},
      {id:"49","dp":"Maine-et-Loire"},
      {id:"50","dp":"Manche"},
      {id:"51","dp":"Marne"},
      {id:"52","dp":"Haute-Marne"},
      {id:"53","dp":"Mayenne"},
      {id:"54","dp":"Meurthe-et-Moselle"},
      {id:"55","dp":"Meuse"},
      {id:"56","dp":"Morbihan"},
      {id:"57","dp":"Moselle"},
      {id:"58","dp":"Nièvre"},
      {id:"59","dp":"Nord"},
      {id:"60","dp":"Oise"},
      {id:"61","dp":"Orne"},
      {id:"62","dp":"Pas-de-Calais"},
      {id:"63","dp":"Puy-de-Dôme"},
      {id:"64","dp":"Pyrénées-Atlantiques"},
      {id:"65","dp":"Hautes-Pyrénées"},
      {id:"66","dp":"Pyrénées-Orientales"},
      {id:"67","dp":"Bas-Rhin"},
      {id:"68","dp":"Haut-Rhin"},
      {id:"69","dp":"Rhône"},
      {id:"70","dp":"Haute-Saône"},
      {id:"71","dp":"Saône-et-Loire"},
      {id:"72","dp":"Sarthe"},
      {id:"73","dp":"Savoie"},
      {id:"74","dp":"Haute-Savoie"},
      {id:"75","dp":"Paris"},
      {id:"76","dp":"Seine-Maritime"},
      {id:"77","dp":"Seine-et-Marne"},
      {id:"78","dp":"Yvelines"},
      {id:"79","dp":"Deux-Sèvres"},
      {id:"80","dp":"Somme"},
      {id:"81","dp":"Tarn"},
      {id:"82","dp":"Tarn-et-Garonne"},
      {id:"83","dp":"Var"},
      {id:"84","dp":"Vaucluse"},
      {id:"85","dp":"Vendée"},
      {id:"86","dp":"Vienne"},
      {id:"87","dp":"Haute-Vienne"},
      {id:"88","dp":"Vosges"},
      {id:"89","dp":"Yonne"},
      {id:"90","dp":"Terr. de Belfort"},
      {id:"91","dp":"Essonne"},
      {id:"92","dp":"Hauts-de-Seine"},
      {id:"93","dp":"Seine-St-Denis"},
      {id:"94","dp":"Val-de-Marne"},
      {id:"95","dp":"Val-D'Oise"},
      {id:"971","dp":"Guadeloupe"},
      {id:"972","dp":"Martinique"},
      {id:"973","dp":"Guyane"},
      {id:"974","dp":"Réunion"},
      {id:"975","dp":"Saint-Pierre-et-Miquelon"},
      {id:"976","dp":"Mayotte"},
      {id:"986","dp":"Wallis-et-Futuna"},
      {id:"987","dp":"Polynésie française"},
      {id:"988","dp":"Nouvelle-Calédonie"}
    ]

  $("#dep").typeahead
    source: (query, process) ->
      data = ["Ain", "Allier", "Ardeche"]
      console.log process(data)
      data
