require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IndicationsController do

  # This should return the minimal set of attributes required to create a valid
  # Indication. As you add validations to Indication, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IndicationsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  before(:all) do
    login_as_admin
  end

  describe "GET index" do
    it "should redirect to login if not connected"
    it "should redirect to intranet home if not authorized"
    it "assigns all indications as @indications" do
      indication = Indication.create! valid_attributes
      get :index, {}, valid_session
      assigns(:indications).should eq([indication])
    end
  end

  describe "GET show" do
    it "assigns the requested indication as @indication" do
      indication = Indication.create! valid_attributes
      get :show, {:id => indication.to_param}, valid_session
      assigns(:indication).should eq(indication)
    end
  end

  describe "GET new" do
    it "assigns a new indication as @indication" do
      get :new, {}, valid_session
      assigns(:indication).should be_a_new(Indication)
    end
  end

  describe "GET edit" do
    it "assigns the requested indication as @indication" do
      indication = Indication.create! valid_attributes
      get :edit, {:id => indication.to_param}, valid_session
      assigns(:indication).should eq(indication)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Indication" do
        expect {
          post :create, {:indication => valid_attributes}, valid_session
        }.to change(Indication, :count).by(1)
      end

      it "assigns a newly created indication as @indication" do
        post :create, {:indication => valid_attributes}, valid_session
        assigns(:indication).should be_a(Indication)
        assigns(:indication).should be_persisted
      end

      it "redirects to the created indication" do
        post :create, {:indication => valid_attributes}, valid_session
        response.should redirect_to(Indication.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved indication as @indication" do
        # Trigger the behavior that occurs when invalid params are submitted
        Indication.any_instance.stub(:save).and_return(false)
        post :create, {:indication => {  }}, valid_session
        assigns(:indication).should be_a_new(Indication)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Indication.any_instance.stub(:save).and_return(false)
        post :create, {:indication => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested indication" do
        indication = Indication.create! valid_attributes
        # Assuming there are no other indications in the database, this
        # specifies that the Indication created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Indication.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => indication.to_param, :indication => { "these" => "params" }}, valid_session
      end

      it "assigns the requested indication as @indication" do
        indication = Indication.create! valid_attributes
        put :update, {:id => indication.to_param, :indication => valid_attributes}, valid_session
        assigns(:indication).should eq(indication)
      end

      it "redirects to the indication" do
        indication = Indication.create! valid_attributes
        put :update, {:id => indication.to_param, :indication => valid_attributes}, valid_session
        response.should redirect_to(indication)
      end
    end

    describe "with invalid params" do
      it "assigns the indication as @indication" do
        indication = Indication.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Indication.any_instance.stub(:save).and_return(false)
        put :update, {:id => indication.to_param, :indication => {  }}, valid_session
        assigns(:indication).should eq(indication)
      end

      it "re-renders the 'edit' template" do
        indication = Indication.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Indication.any_instance.stub(:save).and_return(false)
        put :update, {:id => indication.to_param, :indication => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested indication" do
      indication = Indication.create! valid_attributes
      expect {
        delete :destroy, {:id => indication.to_param}, valid_session
      }.to change(Indication, :count).by(-1)
    end

    it "redirects to the indications list" do
      indication = Indication.create! valid_attributes
      delete :destroy, {:id => indication.to_param}, valid_session
      response.should redirect_to(indications_url)
    end
  end

end
